# Generated by Django 5.0.3 on 2024-04-25 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='file',
            field=models.FileField(upload_to='chatbot', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
