# Generated by Django 5.0.4 on 2024-04-05 01:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CAI', 'Aprendizagem industrial'), ('FIC', 'Formação continuada'), ('CST', 'Curso superior tecnológico'), ('CT', 'Curso Técnico')], max_length=60)),
                ('duration', models.IntegerField()),
                ('duration_type', models.CharField(choices=[('H', 'Horas'), ('S', 'Semestre')], max_length=60)),
                ('area', models.CharField(choices=[('T', 'TI'), ('M', 'MECATRÔNICA'), ('E', 'ELÉTRICA')], max_length=60)),
                ('modality', models.CharField(choices=[('E', 'EAD'), ('P', 'Presencial'), ('H', 'Híbrido')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetDate', models.DateField()),
                ('category', models.CharField(choices=[('CAI', 'Aprendizagem industrial'), ('FIC', 'Formação continuada'), ('CST', 'Curso superior tecnológico'), ('CT', 'Curso Técnico')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Environments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('block', models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timeLoad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('registrationNumber', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classDiv', to='main.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='courseFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursesClass', to='main.courses'),
        ),
        migrations.CreateModel(
            name='CoursesThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.courses')),
                ('themeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='main.theme')),
            ],
        ),
        migrations.CreateModel(
            name='EnviromentsAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviromentsAssigneesCustomUser', to=settings.AUTH_USER_MODEL)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enviromentsAssigneesEnvironment', to='main.environments')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=100)),
                ('assigneeFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioEquipment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Em Aprovamento'), ('3', 'Aprovamento'), ('4', 'Em Revis'), ('5', 'Cancelado')], default='1', max_length=60)),
                ('aproverFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserPlanAprov', to=settings.AUTH_USER_MODEL)),
                ('courseThemeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CourseSignature', to='main.coursesthemes')),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserPlan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Em Aprovamento'), ('3', 'Aprovamento'), ('4', 'Em Revis'), ('5', 'Cancelado')], max_length=60)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=3000)),
                ('planFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanFK', to='main.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=1000)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserSignature', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='signatureFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PlanSignature', to='main.signatures'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('diagnostic', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('MAN', 'Manutenção'), ('ME', 'Melhoria'), ('RE', 'Reunião')], max_length=50)),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em andamento'), ('CA', 'CANCELADA'), ('CO', 'Concluída'), ('EN', 'Encerrada')], max_length=60)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='main.environments')),
                ('reporterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipmentTask', to='main.equipments')),
                ('taskFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefaEquipment', to='main.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
                ('taskFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefaAssig', to='main.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em andamento'), ('CA', 'CANCELADA'), ('CO', 'Concluída'), ('EN', 'Encerrada')], max_length=60)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=350)),
                ('taskFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa', to='main.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='FileTasksStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2200)),
                ('fileType', models.CharField(choices=[('D', 'Document'), ('P', 'Photo')], max_length=60)),
                ('taskStatusFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefaFile', to='main.taskstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('alocationStatus', models.CharField(choices=[('1', 'Rascunho'), ('2', 'Assinalado'), ('3', 'Concluído')], default='1', max_length=60)),
                ('classDivisionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classTeacherDetail', to='main.class')),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserTeacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocationDetailEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.CharField(choices=[('S', 'Segunda'), ('T', 'Terça'), ('Q', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('S', 'Sábado'), ('D', 'Domingo ')], max_length=60)),
                ('hourStart', models.TimeField(auto_now_add=True)),
                ('hourEnd', models.TimeField(auto_now=True)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('endDate', models.DateField(auto_now=True)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherEnvironments', to='main.environments')),
                ('teacherAlocationDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeacherAlocationDetail_env', to='main.teacheralocationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classTeacher', to='main.class')),
                ('reporterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporAlocation', to=settings.AUTH_USER_MODEL)),
                ('themeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='main.theme')),
            ],
        ),
    ]
